// ─────────────────────────────────────────────────────────────────────────────
// tb_rac_systolic_array.v — Verilog testbench for the N×N CORDIC GEMM array
// Pinnacle Quantum Group — April 2026
//
// Reads three input files generated by sim/gen_gemm_vectors.py:
//   gemm_weights.hex   N² angle values in Q0.63 fraction-of-π (row-major)
//   gemm_input.hex     N activation values in Q32.32 (pre-scaled by K_INV)
//   (golden = separate, consumed by cosim_gemm.py)
//
// Flow:
//   1. Reset
//   2. Program all N² PE angles via the (weight_valid, weight_addr,
//      weight_angle) port — one per cycle
//   3. Assert x_valid_in for ONE cycle while x_in[] holds the N
//      activation values
//   4. Wait TOTAL_LATENCY + margin cycles for the systolic pipeline
//      to fully drain
//   5. Capture y_out[] and dump to rtl_gemm_outputs.hex
//
// Build (iverilog):
//   iverilog -g2012 -o tb_rac_systolic_array \
//       tb_rac_systolic_array.v ../rtl/rac_systolic_array.v ../rtl/rac_dsp.v
//   vvp tb_rac_systolic_array
//
// Output:
//   rtl_gemm_outputs.hex — N lines, one per output element
// ─────────────────────────────────────────────────────────────────────────────

`default_nettype none
`timescale 1ns/1ps

module tb_rac_systolic_array;

    // Keep N small for fast iverilog sim — matches gen_gemm_vectors.py --n 4
    localparam integer N        = 4;
    localparam integer WIDTH    = 64;

    // rac_systolic_array exports TOTAL_LATENCY = 2*N + 11 for rac_dsp
    // LATENCY=12. We wait a generous multiple for any edge-timing slack.
    localparam integer WAIT_CYCLES = 2*N + 16;

    reg clk = 0;
    always #5 clk = ~clk;
    reg rst_n;

    // Weight programming port
    reg                          weight_valid;
    reg  [$clog2(N*N)-1:0]       weight_addr;
    reg  signed [WIDTH-1:0]      weight_angle;

    // Activation port
    reg                          x_valid_in;
    reg  signed [WIDTH-1:0]      x_in  [0:N-1];

    // Result port
    wire                         y_valid_out;
    wire signed [WIDTH-1:0]      y_out [0:N-1];

    rac_systolic_array #(
        .N         (N),
        .WIDTH     (WIDTH),
        .INIT_LUT  ("cordic_coarse_lut.mem"),
        .INIT_ATANH("cordic_atanh.mem")
    ) dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .weight_valid (weight_valid),
        .weight_addr  (weight_addr),
        .weight_angle (weight_angle),
        .x_valid_in   (x_valid_in),
        .x_in         (x_in),
        .y_valid_out  (y_valid_out),
        .y_out        (y_out)
    );

    // ── File loaders ───────────────────────────────────────────────────
    reg [WIDTH-1:0] weights_mem [0:N*N-1];
    reg [WIDTH-1:0] input_mem   [0:N-1];

    integer fin;
    integer code;
    reg [2047:0] line;

    task load_hex_array(
        input [255*8:1] path,
        output integer n_loaded
    );
        integer i;
        reg [63:0] v;
        begin
            fin = $fopen(path, "r");
            if (fin == 0) begin
                $display("ERROR: could not open %0s", path);
                $finish;
            end
            i = 0;
            while (!$feof(fin)) begin
                code = $fgets(line, fin);
                if (code <= 0) ;
                else if (line[2047:2040] == "/" && line[2039:2032] == "/")
                    ;  /* comment */
                else begin
                    code = $sscanf(line, "%h", v);
                    if (code == 1) begin
                        if (path[8*8:1] == "gemm_wei") begin
                            if (i < N*N) weights_mem[i] = v;
                        end else begin
                            if (i < N)   input_mem[i]   = v;
                        end
                        i = i + 1;
                    end
                end
            end
            $fclose(fin);
            n_loaded = i;
        end
    endtask

    integer n_weights, n_input;
    integer i;
    integer fout;

    initial begin
        // Reset
        rst_n        = 0;
        weight_valid = 0;
        weight_addr  = 0;
        weight_angle = 0;
        x_valid_in   = 0;
        for (i = 0; i < N; i = i + 1) x_in[i] = 0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // Load vectors
        load_hex_array("gemm_weights.hex", n_weights);
        load_hex_array("gemm_input.hex",   n_input);
        $display("loaded %0d weights, %0d inputs", n_weights, n_input);
        if (n_weights < N*N || n_input < N) begin
            $display("ERROR: insufficient test data");
            $finish;
        end

        // Program PE angles, one per cycle
        for (i = 0; i < N*N; i = i + 1) begin
            weight_valid <= 1'b1;
            weight_addr  <= i[$clog2(N*N)-1:0];
            weight_angle <= $signed(weights_mem[i]);
            @(posedge clk);
        end
        weight_valid <= 1'b0;
        weight_addr  <= 0;
        weight_angle <= 0;
        @(posedge clk);

        // Drive activation vector — one cycle pulse
        for (i = 0; i < N; i = i + 1) x_in[i] = $signed(input_mem[i]);
        x_valid_in <= 1'b1;
        @(posedge clk);
        x_valid_in <= 1'b0;
        for (i = 0; i < N; i = i + 1) x_in[i] <= 0;

        // Wait for pipeline to drain
        repeat (WAIT_CYCLES) @(posedge clk);

        // Dump y_out — one line per output element
        fout = $fopen("rtl_gemm_outputs.hex", "w");
        $fwrite(fout, "// rac_systolic_array RTL outputs — N=%0d\n", N);
        $fwrite(fout, "// format: y[c] in Q32.32 signed\n");
        for (i = 0; i < N; i = i + 1) begin
            $fwrite(fout, "%016x\n", y_out[i]);
        end
        $fclose(fout);
        $display("wrote rtl_gemm_outputs.hex (%0d rows)", N);
        $finish;
    end

    // Timeout safety
    initial begin
        #500000;
        $display("ERROR: testbench timeout");
        $finish;
    end

endmodule

`default_nettype wire
