// ─────────────────────────────────────────────────────────────────────────────
// tb_rac_dsp.v — cosim testbench for rac_dsp.v
// Pinnacle Quantum Group — April 2026
//
// Reads test_vectors.hex (generated by sim/gen_vectors.py), drives
// rac_dsp with one op per cycle, captures outputs once the pipeline
// settles, writes rtl_outputs.hex. A separate diff step (sim/cosim.py)
// then compares against golden.hex.
//
// Build/run under Icarus Verilog:
//     iverilog -g2012 -o tb_rac_dsp \
//         tb_rac_dsp.v \
//         ../rtl/rac_dsp.v
//     vvp tb_rac_dsp
//
// Or Verilator:
//     verilator --binary --top tb_rac_dsp \
//         tb_rac_dsp.v ../rtl/rac_dsp.v
//     ./obj_dir/Vtb_rac_dsp
//
// The testbench expects cordic_coarse_lut.mem + cordic_atanh.mem to be
// accessible from cwd (symlink or copy from rtl/).
// ─────────────────────────────────────────────────────────────────────────────

`default_nettype none
`timescale 1ns/1ps

module tb_rac_dsp;

    localparam integer WIDTH    = 64;
    localparam integer MAX_VECS = 256;
    localparam integer LATENCY  = 12;     // 1 input + 1 coarse + 9 residual + 1 out

    reg clk = 0;
    always #5 clk = ~clk;

    reg rst_n;

    // DUT interface
    reg                          valid_in;
    reg  [2:0]                   op_in;
    reg  signed [WIDTH-1:0]      x_in, y_in, z_in;
    wire                         valid_out;
    wire [2:0]                   op_out;
    wire signed [WIDTH-1:0]      x_out, y_out, z_out;

    rac_dsp #(
        .WIDTH      (WIDTH),
        .INIT_LUT   ("cordic_coarse_lut.mem"),
        .INIT_ATANH ("cordic_atanh.mem")
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .valid_in  (valid_in),
        .op_in     (op_in),
        .x_in      (x_in),
        .y_in      (y_in),
        .z_in      (z_in),
        .valid_out (valid_out),
        .op_out    (op_out),
        .x_out     (x_out),
        .y_out     (y_out),
        .z_out     (z_out)
    );

    // ── Vector storage ────────────────────────────────────────────────
    // test_vectors.hex format per line: "op x y z" with comments. We
    // load into four parallel arrays via a scratch parser.
    reg [2:0]                 v_op  [0:MAX_VECS-1];
    reg signed [WIDTH-1:0]    v_x   [0:MAX_VECS-1];
    reg signed [WIDTH-1:0]    v_y   [0:MAX_VECS-1];
    reg signed [WIDTH-1:0]    v_z   [0:MAX_VECS-1];

    integer n_vecs;
    integer fin;
    reg [2047:0] line;
    integer code;

    task load_vectors;
        integer i;
        integer op_raw;
        reg [63:0] xh, yh, zh;
        begin
            fin = $fopen("test_vectors.hex", "r");
            if (fin == 0) begin
                $display("ERROR: could not open test_vectors.hex");
                $finish;
            end
            i = 0;
            while (!$feof(fin) && i < MAX_VECS) begin
                code = $fgets(line, fin);
                if (code <= 0) begin
                end else if (line[2047:2040] == "/" && line[2039:2032] == "/") begin
                    // comment line, skip
                end else begin
                    code = $sscanf(line, "%x %h %h %h", op_raw, xh, yh, zh);
                    if (code == 4) begin
                        v_op[i] = op_raw[2:0];
                        v_x[i]  = xh;
                        v_y[i]  = yh;
                        v_z[i]  = zh;
                        i = i + 1;
                    end
                end
            end
            $fclose(fin);
            n_vecs = i;
            $display("loaded %0d test vectors", n_vecs);
        end
    endtask

    // ── Output capture ────────────────────────────────────────────────
    reg signed [WIDTH-1:0] out_x [0:MAX_VECS-1];
    reg signed [WIDTH-1:0] out_y [0:MAX_VECS-1];
    reg signed [WIDTH-1:0] out_z [0:MAX_VECS-1];
    integer out_idx;

    always @(posedge clk) begin
        if (rst_n && valid_out) begin
            if (out_idx < MAX_VECS) begin
                out_x[out_idx] <= x_out;
                out_y[out_idx] <= y_out;
                out_z[out_idx] <= z_out;
                out_idx        <= out_idx + 1;
            end
        end
    end

    // ── Stimulus + dump ───────────────────────────────────────────────
    integer fout, i, settle;
    reg [63:0] ux, uy, uz;

    initial begin
        // Reset
        rst_n    = 0;
        valid_in = 0;
        op_in    = 0;
        x_in     = 0; y_in = 0; z_in = 0;
        out_idx  = 0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        load_vectors();

        // Stream vectors: one per cycle with valid_in high.
        for (i = 0; i < n_vecs; i = i + 1) begin
            valid_in <= 1;
            op_in    <= v_op[i];
            x_in     <= v_x[i];
            y_in     <= v_y[i];
            z_in     <= v_z[i];
            @(posedge clk);
        end
        valid_in <= 0;

        // Wait for pipeline to drain.
        for (settle = 0; settle < LATENCY + 4; settle = settle + 1)
            @(posedge clk);

        if (out_idx != n_vecs) begin
            $display("WARN: captured %0d outputs but expected %0d",
                     out_idx, n_vecs);
        end

        // Dump rtl_outputs.hex in the same format as golden.hex
        fout = $fopen("rtl_outputs.hex", "w");
        $fwrite(fout, "// rac_dsp RTL outputs — %0d cases\n", out_idx);
        $fwrite(fout, "// format: x_q3232 y_q3232 z_q3232\n");
        for (i = 0; i < out_idx; i = i + 1) begin
            ux = out_x[i]; uy = out_y[i]; uz = out_z[i];
            $fwrite(fout, "%016x %016x %016x\n", ux, uy, uz);
        end
        $fclose(fout);
        $display("wrote rtl_outputs.hex (%0d rows)", out_idx);
        $finish;
    end

    // Safety net
    initial begin
        #200000;
        $display("ERROR: testbench timeout");
        $finish;
    end

endmodule

`default_nettype wire
